# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Annual Report 2021
logo: logo.png
email: nabeel@lava-brands.ae
description: >- # this means to ignore newlines until "baseurl:"
  Annual Report 2021
baseurl: "/digital_reports/2021" # the subpath of your site, e.g. /blog
# url: "https://www.Baladna.com/en/about-Baladna/about/Investor-Relations/" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://baladna.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: itsnabeel
author: Copyright &copy; 2021
lang: en_US
port: 5000

# Build settings
# theme: minima
markdown: kramdown
sass:
  indentWidth: 2
  style: compact
  precision: 9
  sourcemap: never
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ["en", "ar"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "_sass", "public"]
parallel_localization: true


include:
  - assets
  - ".htaccess"
  - "sitemap.xml"

exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
